"""KLS normal form for checking whether a stabilizer code is LC-equivalent to a CSS code."""

from __future__ import annotations

import numpy as np
import pyzx as zx
from fractions import Fraction

from ..core.stabilizer_code import StabilizerCode

class ZXGraph:
    def __init__(self):
        self.n = 0
        self.k = 0

        # each node identified with the index in the array, input nodes before output nodes
        # each node is represented by a local Clifford "word", which is an element of the group generated by S and H ("decoration" D_i), and a boolean z_i indicating whether there is an additional Z phase AT THE END or not.
        # eg: 
        # I -> ([], False) 
        # S -> (["S"], False) 
        # Z -> ([], True), 
        # S† = SZ -> (["S"], True),  
        # H -> (["H"], False), 
        # HS -> (["H", "S"], False), 
        # HZ -> (["H"], True), 
        # HS† = HSZ -> (["H", "S"], True)
        # SH -> (["S", "H"], False),
        # S†H -> (["S", "S", "S", "H"], False)
        self.vertices : list[tuple[list[str], bool]] = []
        self.edges : set[tuple[int, int]]= set() # (u,v) with u < v
    
    def get_input_output_adjacency(self) -> np.ndarray:
        adj = np.zeros((self.k, self.n), dtype=bool)
        for edge in self.edges:
            u, v = edge
            if u < self.k and v >= self.k:
                adj[u, v - self.k] = True
        return adj
    
    def get_full_adjacency(self) -> np.ndarray:
        adj = np.zeros((self.n + self.k, self.n + self.k), dtype=bool)
        for edge in self.edges:
            u, v = edge
            i = self.vertices.index(u)
            j = self.vertices.index(v)
            adj[i, j] = True
            adj[j, i] = True
        return adj
    
    def neighbors(self, v: int) -> list[int]:
        return [u for u in range(self.n + self.k) if (u, v) in self.edges or (v, u) in self.edges]
    
    def local_complementation(self, v: int):
        neighbors = self.neighbors(v)
        for i in range(len(neighbors)):
            for j in range(i + 1, len(neighbors)):
                p = neighbors[i]
                q = neighbors[j]
                self.apply_cz_edge(p, q)

    def apply_cz_edge(self, u: int, v: int): # toggle the edge (u,v)
        min_u_v = min(u, v)
        max_u_v = max(u, v)
        if (min_u_v, max_u_v) in self.edges: 
            self.edges.remove((min_u_v, max_u_v))
        else: 
            self.edges.add((min_u_v, max_u_v))

    @staticmethod
    def from_pyzx_diagram(diagram: zx.Graph) -> ZXGraph:
        def _pyzx_to_local_clifford(phase: Fraction, edge_type: zx.EdgeType) -> tuple[list[str], bool]:
            if edge_type == zx.EdgeType.SIMPLE:
                if (phase is None or phase == 0):
                    return [], False # I
                elif phase == Fraction(1, 2):
                    return ["S"], False # S
                elif phase == Fraction(1, 1):
                    return [], True # Z
                elif phase == Fraction(3, 2):
                    return ["S"], True # S†
                else:
                    raise ValueError(f"Unexpected vertex phase {phase} in ZX diagram.")
            elif edge_type == zx.EdgeType.HADAMARD: # first z phase is applied, then H edge
                if (phase is None or phase == 0):
                    return ["H"], False # H
                elif phase == Fraction(1, 2):
                    return ["H", "S"], False # SH
                elif phase == Fraction(1, 1):
                    return ["H", "S", "S"], False # ZH
                elif phase == Fraction(3, 2):
                    return ["H", "S", "S", "S"], False # S†H
                else:
                    raise ValueError(f"Unexpected vertex phase {phase} in ZX diagram.")
            
        graph = ZXGraph()
        pyzx_input_boundaries = sorted(diagram.inputs(), key=lambda v: getattr(v, "id", v))
        pyzx_output_boundaries = sorted(diagram.outputs(), key=lambda v: getattr(v, "id", v))
        graph.n = len(pyzx_output_boundaries)
        graph.k = len(pyzx_input_boundaries)
        pyzx_vertices = []

        for input_boundary in pyzx_input_boundaries:
            n = list(diagram.neighbors(input_boundary))
            if len(n) != 1:
                raise ValueError("Expected ZX diagram in encoder form, but found an input vertex with degree != 1.")
            graph.vertices.append(_pyzx_to_local_clifford(diagram.phase(n[0]), diagram.edge_type(diagram.edge(input_boundary, n[0]))))
            pyzx_vertices.append(n[0])

        for output_boundary in pyzx_output_boundaries:
            n = list(diagram.neighbors(output_boundary))
            if len(n) != 1:
                raise ValueError("Expected ZX diagram in encoder form, but found an output vertex with degree != 1.")
            graph.vertices.append(_pyzx_to_local_clifford(diagram.phase(n[0]), diagram.edge_type(diagram.edge(output_boundary, n[0]))))
            pyzx_vertices.append(n[0])

        for edge in diagram.edges():
            u, v = diagram.edge_st(edge)
            if u in pyzx_vertices and v in pyzx_vertices:
                idx_u = pyzx_vertices.index(u)
                idx_v = pyzx_vertices.index(v)
                graph.apply_cz_edge(min(idx_u, idx_v), max(idx_u, idx_v))
        

        return graph
    
    def to_pyzx_diagram(self, cnots: list[tuple[int, int]] = []) -> zx.BaseGraph:
        def _local_clifford_to_pyzx(lc_word: tuple[list[str], bool]) -> tuple[Fraction, zx.EdgeType]:
            # i can assume that input graph is in HK normal form, thus there are only I, S and H decorations (plus additional Z bit)
            deco , z = lc_word
            if deco == [] and not z:
                return (Fraction(0), zx.EdgeType.SIMPLE) # I
            if deco == ["S"] and not z:
                return (Fraction(1, 2), zx.EdgeType.SIMPLE) # S
            if deco == [] and z:
                return (Fraction(1, 1), zx.EdgeType.SIMPLE) # Z
            if deco == ["S"] and z:
                return (Fraction(3, 2), zx.EdgeType.SIMPLE) # S†
            if deco == ["H"] and not z:
                return (Fraction(0), zx.EdgeType.HADAMARD) # H
            if deco == ["H"] and z:
                return (Fraction(1, 1), zx.EdgeType.HADAMARD) # HZ
            else:
                raise ValueError(f"Unexpected local Clifford word {lc_word} in ZX graph.")
            
        def _add_cnots(diagram, inputs):
            for control, target in cnots:
                new_x = diagram.add_vertex(zx.VertexType.X) # place on target

                input_target = inputs[target]
                neighbor = list(diagram.neighbors(input_target))[0]

                e = diagram.edge(input_target, neighbor)
                e_type = diagram.edge_type(e)
                diagram.remove_edge(e)
                diagram.add_edge((new_x, neighbor), edgetype=e_type)
                diagram.add_edge((new_x, input_target), edgetype=zx.EdgeType.SIMPLE)


                new_z = diagram.add_vertex(zx.VertexType.Z) # place on control
                
                input_control = inputs[control]
                neighbor = list(diagram.neighbors(input_control))[0]
                
                e = diagram.edge(input_control, neighbor)
                e_type = diagram.edge_type(e)
                diagram.remove_edge(e)
                diagram.add_edge((new_z, neighbor), edgetype=e_type)
                diagram.add_edge((new_z, input_control), edgetype=zx.EdgeType.SIMPLE)

                diagram.add_edge((new_z, new_x), edgetype=zx.EdgeType.SIMPLE)
            
        diagram = zx.Graph()
        vertex_map = {}
        input_boundaries = []
        output_boundaries = []
        for i, deco in enumerate(self.vertices):
            if i == self.k:
                _add_cnots(diagram, input_boundaries)
            boundary = diagram.add_vertex(zx.VertexType.BOUNDARY)
            if i < self.k:      
                input_boundaries.append(boundary)
            else:
                output_boundaries.append(boundary)

            phase , edge_type = _local_clifford_to_pyzx(deco)
            v = diagram.add_vertex(zx.VertexType.Z, phase=phase)
            vertex_map[i] = v
            diagram.add_edge((boundary, v), edgetype=edge_type)
        
        diagram.set_inputs(input_boundaries)
        diagram.set_outputs(output_boundaries)

        for edge in self.edges:
            u, v = edge
            diagram.add_edge((vertex_map[u], vertex_map[v]), edgetype=zx.EdgeType.HADAMARD)

        return diagram
    
    def is_bipartite(self) -> bool:
        n = self.n + self.k
        colors = np.full(n, -1, dtype=np.int8)

        neighbors_list = [ set() for _ in range(n) ]
        for u, v in self.edges:
            (neighbors_list[u]).add(v)
            (neighbors_list[v]).add(u)

        for start in range(n):
            if colors[start] != -1:
                continue

            colors[start] = 0
            frontier = np.array([start], dtype=int)

            while frontier.size:
                current_color = colors[frontier[0]]
                next_color = 1 - current_color

                neighbors = set()
                for node in frontier:
                    neighbors |= neighbors_list[node]
                neighbors = np.array(list(neighbors), dtype=int)

                if np.any(colors[neighbors] == current_color):
                    return False

                new = neighbors[colors[neighbors] == -1]
                colors[new] = next_color
                frontier = new

        return True

def _code_to_encoder_circuit(code) -> zx.Circuit:
    def _delete_first_row_and_qubit(tab: np.ndarray) -> np.ndarray:
        n = tab.shape[1] // 2
        return np.delete(np.delete(np.delete(tab, 0, axis=0), 0, axis=1) , n-1, axis=1)

    tableau = np.asarray(code.symplectic.copy(), dtype=np.uint8) & 1
    n = code.n
    k = code.k
    original_qubits = list(range(n))

    # Elimination gates are recorded in forward elimination order.
    elimination_gates: list[tuple[str, tuple[int, ...]]] = []
    while tableau.shape[0] > 0:
        cur_n = tableau.shape[1] // 2
        x0 = tableau[0, :cur_n]
        z0 = tableau[0, cur_n:]
        support = np.flatnonzero(x0 | z0)
        if len(support) == 0:
            raise ValueError("Encountered an identity stabilizer row.")

        # 1.) turn every non-identity Pauli in row 0 into Z
        # I = (0|0) --I---> I = (0|0)
        # X = (0|1) --H---> Z = (1|0)
        # Y = (1|1) --HS--> Z = (1|0)
        # Z = (0|1) --I---> Z = (1|0)
        for q in range(cur_n):
            x_q = bool(tableau[0, q])
            z_q = bool(tableau[0, cur_n + q])
            if x_q and z_q:
                # Y -> X under S
                tableau[:, q + cur_n] ^= tableau[:, q]
                tableau[:, [q, q + cur_n]] = tableau[:, [q + cur_n, q]]
                elimination_gates.append(("S", (original_qubits[q],)))
                elimination_gates.append(("H", (original_qubits[q],)))
            elif x_q and not z_q:
                # X -> Z under H
                tableau[:, [q, q + cur_n]] = tableau[:, [q + cur_n, q]]
                elimination_gates.append(("H", (original_qubits[q],)))

        # 2.) make the first qubit Z (pivot) CNOT(0 -> pivot)
        z_support = np.flatnonzero(tableau[0, cur_n:])

        if len(z_support) == 0:
            raise RuntimeError("Failed to convert stabilizer row to Z support.")
        pivot = int(z_support[0])

        if pivot != 0:
            tableau[:, pivot] ^= tableau[:, 0]
            tableau[:, cur_n + 0] ^= tableau[:, cur_n + pivot]

        # 3.) clear all other Zs in row 0 using CNOT(q -> 0)
        # control: (x_c|z_c) --CNOT--> (  x_c  |z_c^z_t)
        # target : (x_t|z_t) --CNOT--> (x_t^x_c|  z_t  )
        for q in range(1, cur_n):
            if tableau[0, cur_n + q] == 1:
                tableau[:, 0] ^= tableau[:, q]
                tableau[:, cur_n + q] ^= tableau[:, cur_n + 0]

                elimination_gates.append(
                    ("CNOT", (original_qubits[q], original_qubits[0]))
                )

        if (
            np.count_nonzero(tableau[0, :cur_n]) != 0
            or np.count_nonzero(tableau[0, cur_n:]) != 1
            or tableau[0, cur_n] != 1
        ):
            raise RuntimeError("Failed to isolate a stabilizer as a single Z.")
        
        # 4.) clear pivot column
        for r in range(1, tableau.shape[0]):
            if tableau[r, cur_n]:
                tableau[r] ^= tableau[0]
            if tableau[r, 0]:
                raise RuntimeError(
                    "A remaining row has X on the pivot qubit."
                )

        # 5.) remove stabilizer and qubit
        tableau = _delete_first_row_and_qubit(tableau)
        del original_qubits[0]

    # encoder = inverse elimination Cliffords
    circuit = zx.Circuit(n)
    circuit.initialize_qubits([True] * (n-k) + [False] * k)
    for name, qubits in reversed(elimination_gates):
        if name == "H":
            circuit.add_gate("HAD", qubits[0])
        elif name == "S":
            # S† = Z phase 3π/2
            circuit.add_gate("ZPhase", qubits[0], phase=3 / 2)
        elif name == "CNOT":
            circuit.add_gate("CNOT", qubits[0], qubits[1])
        
    return circuit 

def _code_to_graph(code) -> ZXGraph:
    # 1.) code -> encoder circuit
    circuit = _code_to_encoder_circuit(code)

    # 2.) Encoder circuit -> zx diagram
    zx_diagram = circuit.to_graph()

    # 3.) zx diagram -> graph like state
    zx.to_graph_like(zx_diagram)

    if not zx.is_graph_like(zx_diagram, strict=True):
        raise ValueError("Expected the ZX diagram to be graph-like, but it was not.")

    # 4.) graph state -> ZXGraph
    graph = ZXGraph.from_pyzx_diagram(zx_diagram)

    return graph

def _hk_normal_form(graph: ZXGraph) -> ZXGraph:
    """Requirements HK normal form:
    1.) graph like state (only Z nodes, one Z node per boundary, no inner Z edges, only H-edges between Z nodes)
    2.) Requirements on LC decorations:
        - only decorations I , S , H allowed (apart from additional Z phases)
        - if vertex has a H decoration, then it cannot have a neighbor with a smaller index
    """ 
    def _h_slide_down(g: ZXGraph, words: list[tuple[list[str], bool]], upper: int, lower: int) -> ZXGraph:
        # (Eq. 13) H_upper |G> = H_lower Z_upper Z_lower prod_{p in A, q in B} CZ_{p,q} |G>
        # with A = N(upper) union {upper}, B = N(lower) union {lower}
        A = set(g.neighbors(upper)) | {upper}
        B = set(g.neighbors(lower)) | {lower}

        words[upper] = ( words[upper][0][:-1] , words[upper][1] ^ True ) # remove H, add Z

        if words[lower][0] and words[lower][0][-1] == "H": # add H, add Z
            words[lower] = ( words[lower][0][:-1] , words[lower][1] ^ True )
        else:
            words[lower] = ( words[lower][0] + ["H"] , words[lower][1] ^ True )

        for p in A:
            for q in B:
                if p == q:
                    words[p] = ( words[p][0] , words[p][1] ^ True ) # add Z
                else:
                    g.apply_cz_edge(p, q)

        return g
    
    def _reduce_trailing_HS(g: ZXGraph, words: list[tuple[list[str], bool]], i: int):
        # (Eq. 12) H_i S_i |G> = S_i^3 prod_{p in N(i)} Z_p prod_{p,q in N(i)} CS_{p,q} |G>
        words[i] = ( words[i][0][:-2] + ["S", "S", "S"], words[i][1] )

        for j in g.neighbors(i):
            words[j][0].extend(["S", "S"])

        # as we handle every subset {p,q} of N(i) twice - as apply_cs_edge(p, q) and apply_cs_edge(q, p) - it effectively applies a CZ between them -> local complementation, with applying S to every neighbor of i (I THINK)
        #
        # for p in g.neighbors(i):
        #     for q in g.neighbors(i):
        #         if p == q:
        #            words[p][0] += ["S"]
        #         else:
        #             g.apply_cs_edge(p, q) 

        for p in g.neighbors(i):
            words[p][0].append("S")

        g.local_complementation(i)

    def _reduce_solo_trailing_SH(g: ZXGraph, words: list[tuple[list[str], bool]], i: int):
        # (Eq. 11) S_i H_i |G> = H_i prod_{p,q in N(i)} CS_{p,q} |G>
        words[i] = (words[i][0][:-2] + ["H"], words[i][1])

        # as we handle every subset {p,q} of N(i) twice - as apply_cs_edge(p, q) and apply_cs_edge(q, p) - it effectively applies a CZ between them -> local complementation, with applying S to every neighbor of i (I THINK)
        #
        # for p in g.neighbors(i):
        #    for q in g.neighbors(i):
        #        if p == q:
        #            words[p][0] += ["S"]
        #        else:
        #            g.apply_cs_edge(p, q)

        for p in g.neighbors(i):
            words[p][0].append("S")

        g.local_complementation(i)

    def _reduce_shared_trailing_SH(g: ZXGraph, words: list[tuple[list[str], bool]], i: int, j: int):
        # (Eq. 11) H_i H_j|G> = Z_i Z_j prod_{p in A, q in B} CZ_{p,q} |G>
        # with A = N(i) union {i}, B = N(j) union {j}
        A = set(g.neighbors(i)) | {i}
        B = set(g.neighbors(j)) | {j}

        words[i] = ( words[i][0][:-1] + ["S", "S"], words[i][1] )
        words[j] = ( words[j][0][:-1] + ["S", "S"], words[j][1] )

        for p in A:
            for q in B:
                if p == q:
                    words[p][0].extend(["S", "S"])
                else:
                    g.apply_cz_edge(p, q)

        return g
    
    def _reduce_word(word: tuple[list[str], bool]) -> tuple[list[str], bool]:
        new_z_bit = word[1]
        deco = word[0]
        # remove identities and push Z back
        changed = True
        while changed:
            new_deco = []
            changed = False
            i = 0

            while i < len(deco):
                if i + 1 < len(deco):
                    a, b = deco[i], deco[i + 1]

                    if (a == "H" and b == "H") or (a == "Z" and b == "Z"):
                        changed = True
                        i += 2
                        continue
                    if a == "S" and b == "S":
                        changed = True
                        new_deco += ["Z"]
                        i += 2
                        continue
                    if a == "Z" and b == "S":
                        changed = True
                        new_deco += ["S", "Z"]
                        i += 2
                        continue
                new_deco.append(deco[i])
                i += 1
            
            deco = new_deco
        
        # remove Z at the end
        while deco and deco[-1] == "Z":
            deco = deco[:-1]
            new_z_bit ^= True

        # make valid decoration
        extended_deco = []
        for i in range(len(deco)):
            if deco[i] == "Z":
                extended_deco += ["S", "S"]
            else:
                extended_deco.append(deco[i])
        
        return extended_deco, new_z_bit
    
    n = graph.n + graph.k

    # 1.) reduce LC decorations to either I, S, or H (and potentially additional Z bit)
    changed = True
    while changed:
        changed = False 

        for i in range(n):
            graph.vertices[i] = _reduce_word(graph.vertices[i])
            if len(graph.vertices[i][0]) < 2:
                continue
            if graph.vertices[i][-2:][0] == ["H", "S"]:
                _reduce_trailing_HS(graph, graph.vertices, i)
                changed = True
                break
            if graph.vertices[i][-2:][0] == ["S", "H"]:
                h_neighbors = [ j for j in graph.neighbors(i) if graph.vertices[j][0][-1:] == ["H"] ]
                if len(h_neighbors) == 0:
                    _reduce_solo_trailing_SH(graph, graph.vertices, i)
                else:
                    _reduce_shared_trailing_SH(graph, graph.vertices, i, h_neighbors[0])
                changed = True
                break

    for i in range(n):
        deco, _ = graph.vertices[i] # should only be I, S, or H decorations (+ additional Z bits) left (aka I, Z, S, SZ = S†, H, HZ)
        if deco not in ([], ["S"], ["H"]):
            raise ValueError(f"After reduction of decorations: Expected only I, S, or H decorations, but got: {deco}.")

      
    # 2.) slides H down
    for x in reversed(range(n)):
        while graph.vertices[x][0] == ["H"]: # x has a Hadamard component
            low_neighbors = [v for v in range(n) if (v, x) in graph.edges]
            if len(low_neighbors) == 0:
                break

            y = min(low_neighbors)
            _h_slide_down(graph, graph.vertices, x, y)

    for x in range(n):
        if not graph.vertices[x][0] in ([], ["H"], ["S"], ["S", "H"]):
            raise ValueError(f"After sliding down all H: Expected only I, S, H decorations, but got: {graph.vertices[x][0]}.")
    # now should only have decorations I , H, S, SH
    
    # 3.) cleanup SH decorations
    for i in range(n):
        if graph.vertices[i][0] == ["S", "H"]: # apply Eq. 11
            graph.vertices[i] = (["H"], graph.vertices[i][1])
            for p in graph.neighbors(i):
                if graph.vertices[p][0] == []:
                    graph.vertices[p] = (["S"], graph.vertices[p][1])
                if graph.vertices[p][0] == ["S"]:
                    graph.vertices[p] = ([], graph.vertices[p][1] ^ True)
                else:
                    raise ValueError(f"Expected only I, S decorations in the neighborhood of a H-decorated vertex, but got: {graph.vertices[p][0]}")
            graph.local_complementation(i)

    return graph

def _kls_normal_form(graph_hk: ZXGraph) -> ZXGraph:
    """Additional requirements KLS normal form:
    1.) input nodes have no non-I LC decoration, and no edges between input nodes
    2.) the input-output adjacency matrix is in RREF
    3.) the pivot columns of the input-output adjacency matrix have no non-I LC decorations, and no edges between pivot vertices
    """
    # 1.) set input vertices to have no decoration and no edges
    for q in range(graph_hk.k):
        graph_hk.vertices[q] = 0
        for i in range(q + 1, graph_hk.k):
            if (q, i) in graph_hk.edges:
                graph_hk.edges.remove((q, i))

    # 2.) bring the IO-adjacency matrix into RREF
    adj = graph_hk.get_input_output_adjacency()
  
    pivot_row = 0
    cnots_gates = []
    for c in range(graph_hk.n):
        pivot_candidates = np.flatnonzero(adj[pivot_row:, c])
        if len(pivot_candidates) == 0:
            continue
        pivot = pivot_row + int(pivot_candidates[0])

        if pivot != pivot_row:
            adj[[pivot_row, pivot]] = adj[[pivot, pivot_row]]
            cnots_gates.append((pivot_row, pivot)) # swap = 3 CNOTs
            cnots_gates.append((pivot, pivot_row))
            cnots_gates.append((pivot_row, pivot))

        for r in range(graph_hk.k):
            if r != pivot_row and adj[r, c]:
                adj[r] ^= adj[pivot_row]
                cnots_gates.append((pivot_row, r))
        pivot_row += 1

        if pivot_row == graph_hk.k:
            break

    # 3.) simplify the graph with the added CNOTS
    zx_diagram = graph_hk.to_pyzx_diagram(cnots=cnots_gates)

    zx.to_graph_like(zx_diagram)

    # 4.) graph state -> ZXGraph
    graph = ZXGraph.from_pyzx_diagram(zx_diagram)
    return graph

def is_lceq_css_kls(code: StabilizerCode) -> bool:
    """Check if a stabilizer code is LC-equivalent to a CSS code by converting it into KLS normal form and checking if the resulting graph state is bipartite.

    1.) Convert the stabilizer code into a clifford encoder circuit.
    2.) Convert the encoder circuit into a ZX diagram.
    3.) Simplify the ZX diagram into a graph-like state, aka a graph with local Clifford decorations on the vertices.
    4.) Convert the graph-like state into HK normal form, while treating the input vertices as output vertices.
    5.) Convert the HK normal form into KLS normal form, treating the input vertices as inputs again.

    The conversion from stabilizer code into a graph state can be done in O(n^3) time an the efficient algorithm for equivalence checking of graph states runs in O(n^4) time, so the overall runtime of this algorithm should be O(n^3) which is very efficient.
    """
    graph = _code_to_graph(code)
    graph_hk = _hk_normal_form(graph)
    graph_kls = _kls_normal_form(graph_hk)
    return graph_kls.is_bipartite()
